language: node_js
node_js:
  - "0.12"
before_install: npm install -g grunt-cli
install: npm install
addons:
  code_climate:
      repo_token: aff33f...
after_script:
  - codeclimate-test-reporter < lcov.info
