language: node_js
node_js:
  - "0.12"
before_install: npm install -g grunt-cli
install: npm install
addons:
  code_climate:
      repo_token: 35acd8441b1656427e25db959771ca7a98d3ffb18df8b859ff48ee0cff0313ab
after_script:
  - codeclimate-test-reporter < lcov.info
